---
- name: Run debsums check
  shell: debsums -c 1> /var/log/debsums.output 2> /var/log/debsums.err
  when:
    (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and
    (debsums_ubuntu_check is defined and debsums_ubuntu_check)
  tags: debsums
  ignore_errors: yes
